<?php
/** @var \Packetery\Checkout\Block\Adminhtml\Order\AddressDetail $block */
/** @var \Packetery\Checkout\Model\Order $packeteryOrder */
$packeteryOrder = $block->getData('order');
$packeteryMagentoOrder = $block->getData('magentoOrder');
$order = $block->getData('magentoOrder');
$packeteryAddress = $packeteryOrder->getRecipientAddress();
$shippingMethod = $packeteryMagentoOrder->getShippingMethod(true)->getData('method');
$methodCode = \Packetery\Checkout\Model\Carrier\MethodCode::fromString($shippingMethod);
?>

<?php if (\Packetery\Checkout\Model\Carrier\Methods::isAnyAddressDelivery($methodCode->getMethod())) { ?>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Information')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <?php if (!$packeteryOrder->isAddressValidated()) { ?>
                <p><strong><?= $block->escapeHtml(__('Address was not validated')); ?></strong></p>
            <?php } ?>

            <?php if ($packeteryOrder->isAddressValidated()) { ?>
                <p><strong><?= $block->escapeHtml(__('Order has following validated address:')); ?></strong></p><br>
                <address class="admin__page-section-item-content">
                    <?php if ($packeteryOrder->isAddressValidated()) { ?>
                        <p><strong><?= $block->escapeHtml(__('Street')) ?></strong>: <?= $block->escapeHtml($packeteryAddress->getStreet()); ?></p>
                        <p><strong><?= $block->escapeHtml(__('House number')) ?></strong>: <?= $block->escapeHtml($packeteryAddress->getHouseNumber()); ?></p>
                        <p><strong><?= $block->escapeHtml(__('City')) ?></strong>: <?= $block->escapeHtml($packeteryAddress->getCity()); ?></p>
                        <p><strong><?= $block->escapeHtml(__('Country Code')) ?></strong>: <?= $block->escapeHtml($packeteryAddress->getCountryId()); ?></p>
                        <p><strong><?= $block->escapeHtml(__('County')) ?></strong>: <?= $block->escapeHtml($packeteryAddress->getCounty()); ?></p>
                        <p><strong><?= $block->escapeHtml(__('Zip')) ?></strong>: <?= $block->escapeHtml($packeteryAddress->getZip()); ?></p>
                        <a target="_blank" href="https://www.google.com/maps/search/?api=1&query=<?= $block->escapeHtml($packeteryAddress->getLatitude()); ?>,<?= $block->escapeHtml($packeteryAddress->getLongitude()); ?>"><?= $block->escapeHtml(__('GPS coordinates')); ?></a>
                    <?php } ?>
                </address>
            <?php } ?>
        </div>
    </div>
</section>

<?php } ?>
